import Head from 'next/head'
import Script from 'next/script'
import { useEffect, useState } from 'react'
import { Button } from "@nextui-org/react";
import sampleImage from "./sample.png"
var getImageOutline = require('image-outline/browser');

export default function Home() {
  const [zoom, setZoom] = useState(100);
  const [simplifyThreshold, setSimplifyThreshold] = useState(10);
  const [editor, setEditor] = useState(null);
  const [polygonCount, setPolygonCount] = useState(0);
  // const [imageEl, setImageEl] = useState(null);

  function addPolygon(editor, threshold) {
    var polygon = getImageOutline(window.__editorImageEl, {simplifyThreshold: threshold});
    setPolygonCount(polygon.length);
    editor.addShapeJson({"type": "Polygon",
      // "points": "100,0 329,271 295,314 295,365 333,432 413,400 452,350 432,292 385,256",
      "points": polygon.map(p => p.x + "," + p.y).join(" "),
      "strokeColor": "#FF00FF",
      "strokeWidth": 2});
  }

  useEffect(() => {
    if (window.editorLoaded) return;
    window.editorLoaded = true;
    
    var shapeManager = new ShapeManager("shapesCanvas",
                                          width, height,
                                          options);
    setEditor(shapeManager);
    
    const {width, height, src} = sampleImage;
    const options = {}
    var image = new Image();
    window.__editorImageEl = image;

    image.onload = function() {
      addPolygon(shapeManager, simplifyThreshold);
    }
    image.src = src;
    
    
    
    
    
    

  }, []);
  return (
    <div className="physics-editor">

      <Head>
        <title>Physics Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/js/jquery-1.11.3.min.js" strategy="beforeInteractive" />
      <Script src="/js/raphael.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/line.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/ellipse.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/rect.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/polygon.js" strategy="beforeInteractive" />
      <Script src="/js/shapeManager.js" strategy="beforeInteractive" />

      <main>
        <div className='image-wrapper'>
        <img src={sampleImage.src} alt="sample"
          style={{width: sampleImage.width, height: sampleImage.height}} />
        <div id="shapesCanvas" style={{width: sampleImage.width, height: sampleImage.height}}></div>
        </div>
        <Button.Group>
        <Button onPress={()=>{
          editor.deleteAllShapes();
          const newThreshold = simplifyThreshold + 10;
          setSimplifyThreshold(newThreshold);
          addPolygon(editor, newThreshold);
        }}>-</Button>
        <Button disabled>{polygonCount}</Button>
        <Button onPress={()=>{
          editor.deleteAllShapes();
          const newThreshold = simplifyThreshold - 10;
          setSimplifyThreshold(newThreshold);
          addPolygon(editor, newThreshold);
        }}>+</Button>
      </Button.Group>
      </main>
    </div>
  )
}
