import Head from 'next/head'

import Script from 'next/script'
import { Grid, Collapse, Text, Container, Row, Button, Dropdown } from "@nextui-org/react";
import FileTree from '../common/components/FileTree';
import styles from '../styles/Home.module.css'
import FS from "../common/fs";
import AssetProperties from '../common/components/AssetProperties';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Phaser Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Script src="/js/jquery-1.11.3.min.js" strategy="beforeInteractive" />
      <Script src="/js/raphael.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/line.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/ellipse.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/rect.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/polygon.js" strategy="beforeInteractive" />
      <Script src="/js/shapeManager.js" strategy="beforeInteractive" />

      <main className="editor-container">
        <Container fluid style={{maxWidth: "100vw"}}>
          <Row>
            <Button.Group>
              <Button onPress={() => {
                var con = confirm("Are you sure you want to delete all assets and code and start new project?");
                if (con) {
                  FS.clear();
                }
              }}>New Project</Button>
            </Button.Group>
          </Row>
          <Row fluid>
            <Grid.Container gap={1}>
              <Grid xs={2}>
                <FileTree />
              </Grid>
              <Grid xs={8}>
                d
              </Grid>
              <Grid xs={2}>
                <AssetProperties />
              </Grid>
            </Grid.Container>
          </Row>
        </Container>
      </main>
    </div>
  )
}
