import Head from 'next/head'

import Script from 'next/script'
import { Grid, Collapse, Text, Container, Row, Button, Dropdown } from "@nextui-org/react";
import FileTree from '../common/components/FileTree';
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import FS from "../common/fs";
import AssetProperties from '../common/components/AssetProperties';
import GameView from '../common/components/GameView';

export default function Home() {
  const [propertiesOfFile, setPropertiesOfFile] = useState(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Phaser Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Script src="/js/jquery-1.11.3.min.js" strategy="beforeInteractive" />
      <Script src="/js/raphael.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/line.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/ellipse.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/rect.js" strategy="beforeInteractive" />
      <Script src="/js/shapes/polygon.js" strategy="beforeInteractive" />
      <Script src="/js/shapeManager.js" strategy="beforeInteractive" />

      <Script src="/gamecode/lib/phaser.min.js" strategy="beforeInteractive" />
      <Script src="/gamecode/lib/mousetrap.min.js" strategy="beforeInteractive" />
      <Script src="/gamecode/lib/eventemitter.js" strategy="beforeInteractive" />
      <Script src="/gamecode/superEventEmitter.js" strategy="beforeInteractive" />
      <Script src="/gamecode/playersConfig.js" strategy="beforeInteractive" />
      <Script src="/gamecode/playerState.js" strategy="beforeInteractive" />
      <Script src="/gamecode/multiplayer.js" strategy="beforeInteractive" />
      <Script src="/gamecode/gamescene.js" strategy="beforeInteractive" />

      <main className="editor-container">
        <Container fluid style={{maxWidth: "100vw"}}>
          <Row>
            <Button.Group>
              <Button onPress={() => {
                var con = confirm("Are you sure you want to delete all assets and code and start new project?");
                if (con) {
                  FS.clear();
                }
              }}>New Project</Button>
            </Button.Group>
          </Row>
          <Row fluid>
            <Grid.Container gap={1}>
              <Grid xs={2}>
                <FileTree onProperties={(filename)=> setPropertiesOfFile(filename)} />
              </Grid>
              <Grid xs={propertiesOfFile?8:10}>
                <GameView />
              </Grid>
              {propertiesOfFile &&
                <Grid xs={2}>
                  <AssetProperties filename={propertiesOfFile} onClose={()=>setPropertiesOfFile(null)} />
                </Grid>}
            </Grid.Container>
          </Row>
        </Container>
      </main>
    </div>
  )
}
