import Head from 'next/head'
import { Delete } from 'react-iconly';
import { Grid, Collapse, Text, Container, Row, Button, Dropdown} from "@nextui-org/react";
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import FS from "../common/fs";

//handle files dropped in
function scanFiles(item, container) {
  let elem = document.createElement("li");
  elem.innerHTML = item.name;
  container.appendChild(elem);
 
//  if (item.isDirectory) {
//     let directoryReader = item.createReader();
//     let directoryContainer = document.createElement("ul");
//     container.appendChild(directoryContainer);
//     directoryReader.readEntries(function(entries) {
//         entries.forEach(function(entry) {
//           scanFiles(entry, directoryContainer);
//       });
//     });
//   }
}

export default function Home() {
  const [files, setFiles] = useState([]);
  useEffect(()=>{
    const endWatch = FS.watchDir("/assets", files => setFiles(files))
    // FS.list("/assets").then(files => {
    //   console.log("LS", files);
    //   setFiles(files);
    // })
    return endWatch;
  },[])
  console.log("A",files);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="editor-container">
        <Container fluid>
          <Row>
          <Button.Group>
            <Button onPress={()=>{
              var con = confirm("Are you sure you want to delete all assets and code and start new project?");
              if (con) {
                FS.clear();
              }
            }}>New Project</Button>
          </Button.Group>
          </Row>
        <Row>
          <Grid.Container gap={1}>
            <Grid xs={2}>
              <Container>
                <Collapse.Group accordion={false}>
                  <Collapse expanded={files && files.length>0} title="Assets">
                    <div id='dropzone' 
                      onDragOver={(event)=>{
                          event.preventDefault();
                    }}
                    onDrop={(event)=>{
                      let items = event.dataTransfer.items;
                      event.preventDefault();
                      // const curFiles = files.splice(0);
                      for (let i=0; i<items.length; i++) {
                        let item = items[i].webkitGetAsEntry();
                        
                        if (item) {
                          //TODO: if file already exists, replace it
                          FS.write("/assets", item);
                          // curFiles.push(item.name);
                          // scanFiles(item, listing);
                        }
                      }
                      // console.log(curFiles)
                      // setFiles(curFiles);
                    }}>
                      <div id="boxtitle">
                        Drop Images + MP3s here
                      </div>
                    </div>
                    <ul>
                      {files.map((item, index)=>{
                        return (
                          <Dropdown>
                            <Dropdown.Button light className='file-button'>
                              {item}
                            </Dropdown.Button>
                            <Dropdown.Menu
                              onAction={(key)=>{
                                if (key === "delete") {
                                  var con = confirm("Are you sure you want to delete this asset?");
                                  if (con) {
                                    FS.remove("/assets", item);
                                  }
                                }
                              }}
                              variant="light"
                              aria-label="Actions"
                            >
                              <Dropdown.Item key="preview">Preview</Dropdown.Item>
                              <Dropdown.Item key="collision">Collision Editor</Dropdown.Item>
                              <Dropdown.Item key="delete" color="error" withDivider>
                                Delete file
                              </Dropdown.Item>
                            </Dropdown.Menu>
                          </Dropdown>
                        )
                        // return <li className='file-item' key={item}>
                        //   {item}
                        //   <a onClick={()=> {
                        //     var con = confirm("Are you sure you want to delete this asset?");
                        //     if (con) {
                        //       FS.remove("/assets", item);
                        //     }
                        //   }}><Delete size={15} set="bold" primaryColor="red"/></a>
                        // </li>
                      })}
                    </ul>
                  </Collapse>
                  <Collapse expanded title="Code">
                    <Text>
                      asdas
                    </Text>
                  </Collapse>
                </Collapse.Group>
              </Container>
            </Grid>
            <Grid xs={8}>
              d
            </Grid>
            <Grid xs={2}>
              f
            </Grid>
          </Grid.Container>
          </Row>
        </Container>
      </main>
    </div>
  )
}
